shared:
    image: mreichelt/android

jobs:
    A:
        steps:
            - echo: echo $PWD
            - permission: chmod +x ./gradlew
            - build: ./gradlew check assemble
        requires: [~commit, ~pr]

    # B will run after A
    B:
        steps:
            - echo: echo test
        requires: [A]

    # C will run after B
    C:
        steps:
            - echo: echo test
        requires: [B]
